development:
    adapter: redis
    url: redis://localhost:6379/1

test:
  adapter: async

production: &production
  :url:  <%= ENV["REDIS_URL"] %>
  :host: <%= ENV["REDIS_HOST"] %>
  :port: <%= ENV["REDIS_PORT"] %>
  :password: <%= ENV["REDIS_PASSWORD"] %>
  :inline: true
  :timeout: 1
